### ISSUE TITLE
GraphQL documents

### ISSUE THREAD

**Issue by Lenin7** [sibelius/ReactNavigationRelay#1]
What documents should we add to the database to make this work with 
[https://github.com/entria/graphql-dataloader-boilerplate](https://github.com/entria/graphql-dataloader-boilerplate) ?

I have this document in my user collection, but UserList always shows up as empty.
```
{
    "_id": "507f1f77bcf86cd799439011",
    "name": "someuser",
    "email": "someuser@mail.com",
    "active": true
}
```

Any ideas? Thanks

**Comment by sibelius** [comment]
U can use the REPL of graphql-dataloader-boilerplate to add some users to your server (https://github.com/entria/graphql-dataloader-boilerplate#repl-server)

something like this: 
```jsx
yarn repl
awesome > new M.User({name: 'someuser', email: 'someuser@gmail.com', password: 'somepassword'}).save()
```

**Comment by sibelius** [comment]
@Lenin7 did this solved your problem?

**Comment by Lenin7** [comment]
Relay refuses to get data from the GraphQL server for some reason. 
I get no errors or warnings, and it's basically stuck in the "loading" icon.

I'v only tested this on Windows/Android so far. Not sure if it's related.
I'll test this on Mac/iOS in a few hours and let you know

**Comment by sibelius** [comment]
u need to use adb reverse on android

try to use ip of your machine instead of localhost

**Comment by Lenin7** [comment]
It's working now. I had a typo in my mongodb documents.
Thanks!
