### ISSUE TITLE
Does "Relay Modern" change anything?

### ISSUE THREAD

**Issue by superquest** [sibelius/ReactNavigationRelay#2]
I know [relay modern](https://facebook.github.io/relay/docs/relay-modern.html) is backwards-compatible ... just asking if new things are possible?

**Comment by sibelius** [comment]
relay modern changed a lot of things, I'll came with another simple boilerplate using React Native and Relay Modern soon

**Comment by sibelius** [comment]
The migration was done here: https://github.com/sibelius/ReactNavigationRelay/pull/5

one commit at a time to make the transition easier to everybody

**Comment by cellis** [comment]
@sibelius how does caching work. Will this still work with [rn-relay-cache-manager](github.com/helielson/rn-relay-cache-manager)?
